### ISSUE TITLE
`:` can not be processed

### ISSUE THREAD

**Issue by dhebbeker** [me21/EspArduinoExceptionDecoder#1]
My traces look like this:

```plain
Backtrace: 0x4037790e:0x3fc94400 0x4037ae81:0x3fc94420 0x4038104d:0x3fc94440 0x40378a7b:0x3fc944c0 0x40378ba1:0x3fc944f0 0x40378c70:0x3fc94510 0x4206bb27:0x3fc94540 0x4205d4fa:0x3fc94560 0x420057ef:0x3fc94580 0x42078aa1:0x3fc945b0 0x403752d9:0x3fc945d0 0x403752fe:0x3fc945f0 0x403787e9:0x3fc94610 0x420791d7:0x3fcf4d70 0x42010f5a:0x3fcf4d90 0x4037c048:0x3fcf4db0
```

On an ESP32-S3.

The output of the script is

```plain
stack:
Traceback (most recent call last):
  File "/home/dhebbeker/temp/EspArduinoExceptionDecoder/decoder.py", line 319, in <module>
    print_result(parser, resolver, args.platform, args.full, args.stack_only)
  File "/home/dhebbeker/temp/EspArduinoExceptionDecoder/decoder.py", line 271, in print_result
    print_stack_full(parser.stack, resolver)
  File "/home/dhebbeker/temp/EspArduinoExceptionDecoder/decoder.py", line 235, in print_stack_full
    print(line.offset + ":")
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Comment by GUVWAF** [comment]
Looks like it should be `print(str(line.offset) + ":")`.
